//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_article
    {
        public int ID { get; set; }
        public int BloggerID { get; set; }
        public int CategoryID { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public string Image { get; set; }
        public Nullable<int> Views { get; set; }
        public string Date { get; set; }
        public byte Status { get; set; }
    
        public virtual tbl_blogger tbl_blogger { get; set; }
        public virtual tbl_category tbl_category { get; set; }
    }
}
